name: provider_demo
description: "A new Flutter project."

publish_to: 'MO4 Network'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.4.1
  get_it: ^7.6.7
  provider: ^6.1.2
  animated_read_more_text: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true